drop database if exists anjali;
create database if not exists anjali;
use anjali;
create table example1 (id1 int auto_increment primary key,name varchar(20) not null,age int,mobile varchar(10) unique,email varchar(20) unique,address varchar(30) default 'kawardha');
create table example2(id2 int auto_increment primary key,id1 int,foreign key (id1) references example1(id1));
insert into example1 values(id1,'user1',17,'1234567890','user1@gmail.com',address),(id1,'user2',18,'1234567891','user2@gmail.com',address),(id1,'user3',19,'1234567892','user3@gmail.com',address);
select * from example1;
insert into example2 values(id2,1),(id2,2),(id2,3);
select * from example2;
alter table example2 modify column id1 int not null;
delete from example2 where id2=1;
alter table example2 auto_increment=1;
create table example3 (id int primary key auto_increment , name varchar(10), gender char(255));
insert into example3 values(id,'pritam','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su.');
select * from example3;
create table example4 (id int primary key auto_increment, name char(25) default 'anjali' , mobile char(10), gender enum('male','female'),id1 int not null,foreign key (id1) references example4(id));
create table example5 (id int primary key auto_increment, name char(25) default 'anjali' , mobile char(10), gender enum('male','female'),id1 int,foreign key (id1) references example4(id1));
drop table example4;
drop table example5;
insert into example4 values(id,name,'9445312345','female',1),(id,'sanam','9345312345','male',2);
-- create table example6 (id int primary key auto_increment, name char(25) default 'anjali' , mobile char(10), gender enum('male','female'),id1 int,foreign key (id1) references example6(id1));
-- create table example6 (id int primary key auto_increment, name char(25) default 'anjali' , mobile char(10), gender enum('male' ,'female'),id1 int,foreign key (id1) references example6(id1));
-- create table example6 (id int primary key auto_increment, name char(25) default 'anjali' , mobile char(10), gender enum('male' ,'female'),id1 int,foreign key (id) references example6(id1));
desc example4;
desc example5;
select * from example4;